services:
  crowdsec:
    image: crowdsecurity/crowdsec
    restart: ${RESTART_POLICY}
    networks:
      crowdsec:
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      COLLECTIONS: "crowdsecurity/nginx"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - 'socket-proxy'
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/

  diun:
    image: crazymax/diun:latest
    command: serve
    restart: ${RESTART_POLICY}
    labels:
      - "diun.enable=true"
    networks:
      crowdsec:
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      TZ: ${TZ}
      DIUN_WATCH_WORKERS: 20
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_WATCH_JITTER: 30s
      DIUN_PROVIDERS_DOCKER: true
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: true
      DIUN_NOTIF_NTFY_ENDPOINT: https://ntfy.sh
      DIUN_NOTIF_NTFY_TOPIC: UOZt3Rq4VidyJyzt
      DIUN_NOTIF_NTFY_PRIORITY: 3
      DIUN_NOTIF_NTFY_TAGS: mattermost-hcloud
      DIUN_NOTIF_NTFY_TIMEOUT: 10s
      DIUN_NOTIF_NTFY_TEMPLATETITLE: "{{ .Entry.Image }} released"
      DIUN_NOTIF_NTFY_TEMPLATEBODY: |
        Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
    depends_on:
      - 'socket-proxy'
    volumes:
      - "./diun_data:/data"

  socket-proxy:
    container_name: socket-proxy
    image: lscr.io/linuxserver/socket-proxy:latest
    restart: ${RESTART_POLICY}
    networks:
      crowdsec:
    environment:
      INFO: 1
      CONTAINERS: 1
      POST: 0
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      DISTRIBUTION: 0
      EXEC: 0
      GRPC: 0
      IMAGES: 0
      NETWORKS: 0
      NODES: 0
      PLUGINS: 0
      SERVICES: 0
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 0
      VOLUMES: 0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    read_only: true
    tmpfs:
      - /run

  nginx:
    depends_on:
      - mattermost
    container_name: nginx_mattermost
    image: nginx:${NGINX_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    runtime: runsc
    labels:
      - crowdsec.enable=true
      - crowdsec.labels.type=nginx
    ## https://docs.crowdsec.net/docs/next/data_sources/docker#use_container_labels
    cap_drop:
      - NET_RAW
      - SYS_CHROOT
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
      - /var/log/nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d:ro
      - ${NGINX_DHPARAMS_FILE}:/dhparams4096.pem
      - ${CERT_PATH}:/cert.pem:ro
      - ${KEY_PATH}:/key.pem:ro
      - shared-webroot:/usr/share/nginx/html
    environment:
      - TZ
      - MM_URL
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t 1", "--spider", "{$MM_URL}:${HTTP_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mattermost:
    ports:
      - ${CALLS_PORT}:${CALLS_PORT}/udp
      - ${CALLS_PORT}:${CALLS_PORT}/tcp


volumes:
  crowdsec-db:
  crowdsec-config:
  # Shared volume for Let's Encrypt certificate renewal with a webroot
  shared-webroot:
    name: shared-webroot

networks:
  crowdsec:
    driver: bridge
  # This network name is being used for Let's Encrypt certificate renewal
  default:
    name: mattermost
    driver: bridge
